name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_ID = "Ov23lipSDNWM2ppTo4tH"
GITHUB_OWNER = "RunWang925"
GITHUB_REPO = "NavSphere"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://xn--grq73v8vvp61a.dpdns.org/api/auth"
NEXT_PUBLIC_API_URL="https://xn--grq73v8vvp61a.dpdns.org/"

